name: multiavatar_plus
description: Multiavatar is a multicultural avatar maker. 12 billion unique multicultural avatars 
version: 0.3.0-beta.1
homepage: https://github.com/nemr0/multiavatar_plus
repository: https://github.com/nemr0/multiavatar_plus
documentation: https://github.com/nemr0/multiavatar_plus

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
